[package]
name = "core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
reqwest = "0.11.9"
tokio = { version = "1.17.0", features = ["fs", "rt-multi-thread"] }
json = "0.12.4"
futures = "0.3.21"
rusqlite = { version = "0.26.3", features = ["bundled"] }
